export const GET_VEO_PRICE_SUCCESS = "GET_VEO_PRICE_SUCCESS"
export const GET_VEO_PRICE_FAILURE = "GET_VEO_PRICE_FAILURE"
export const GET_VEO_PRICE_STARTED = "GET_VEO_PRICE_STARTED"

export const SET_LANGUAGE_SUCCESS = "SET_LANGUAGE_SUCCESS"
export const SET_LANGUAGE_FAILURE = "SET_LANGUAGE_FAILURE"
export const SET_LANGUAGE_STARTED = "SET_LANGUAGE_STARTED"

export const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS"
export const GET_LANGUAGE_FAILURE = "GET_LANGUAGE_FAILURE"
export const GET_LANGUAGE_STARTED = "GET_LANGUAGE_STARTED"
