export const GET_VEO_PRICE_SUCCESS = "GET_VEO_PRICE_SUCCESS"
export const GET_VEO_PRICE_FAILURE = "GET_VEO_PRICE_FAILURE"
export const GET_VEO_PRICE_STARTED = "GET_VEO_PRICE_STARTED"

export const SET_LANGUAGE_SUCCESS = "SET_LANGUAGE_SUCCESS"
export const SET_LANGUAGE_FAILURE = "SET_LANGUAGE_FAILURE"
export const SET_LANGUAGE_STARTED = "SET_LANGUAGE_STARTED"

export const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS"
export const GET_LANGUAGE_FAILURE = "GET_LANGUAGE_FAILURE"
export const GET_LANGUAGE_STARTED = "GET_LANGUAGE_STARTED"

export const SET_CURRENCY_SUCCESS = "SET_CURRENCY_SUCCESS"
export const SET_CURRENCY_FAILURE = "SET_CURRENCY_FAILURE"
export const SET_CURRENCY_STARTED = "SET_CURRENCY_STARTED"

export const GET_CURRENCY_SUCCESS = "GET_CURRENCY_SUCCESS"
export const GET_CURRENCY_FAILURE = "GET_CURRENCY_FAILURE"
export const GET_CURRENCY_STARTED = "GET_CURRENCY_STARTED"

export const GET_ACTIVE_MARKETS_SUCCESS = "GET_ACTIVE_MARKETS_SUCCESS"
export const GET_ACTIVE_MARKETS_FAILURE = "GET_ACTIVE_MARKETS_FAILURE"
export const GET_ACTIVE_MARKETS_STARTED = "GET_ACTIVE_MARKETS_STARTED"

export const GET_EXPIRED_MARKETS_SUCCESS = "GET_EXPIRED_MARKETS_SUCCESS"
export const GET_EXPIRED_MARKETS_FAILURE = "GET_EXPIRED_MARKETS_FAILURE"
export const GET_EXPIRED_MARKETS_STARTED = "GET_EXPIRED_MARKETS_STARTED"

export const GET_HEIGHT_SUCCESS = "GET_HEIGHT_SUCCESS"
export const GET_HEIGHT_FAILURE = "GET_HEIGHT_FAILURE"
export const GET_HEIGHT_STARTED = "GET_HEIGHT_STARTED"

export const GET_MARKET_SUCCESS = "GET_MARKET_SUCCESS"
export const GET_MARKET_FAILURE = "GET_MARKET_FAILURE"
export const GET_MARKET_STARTED = "GET_MARKET__STARTED"

export const SEND_REQUEST_SUCCESS = "SEND_REQUEST_SUCCESS"
export const SEND_REQUEST_FAILURE = "SEND_REQUEST_FAILURE"
export const SEND_REQUEST_STARTED = "SEND_REQUEST_STARTED"

export const GET_IP_SUCCESS = "GET_IP_SUCCESS"
export const GET_IP_FAILURE = "GET_IP_FAILURE"
export const GET_IP_STARTED = "GET_IP_STARTED"

export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS"
export const GET_ACCOUNT_FAILURE = "GET_ACCOUNT_FAILURE"
export const GET_ACCOUNT_STARTED = "GET_ACCOUNT_STARTED"

export const SET_ACCOUNT_SUCCESS = "SET_ACCOUNT_SUCCESS"

export const SET_CHANNEL_PENDING_SUCCESS = "SET_CHANNEL_PENDING_SUCCESS"
export const SET_CHANNEL_PENDING_FAILURE = "SET_CHANNEL_PENDING_FAILURE"

export const GET_CHANNEL_PENDING_SUCCESS = "GET_CHANNEL_PENDING_SUCCESS"
export const GET_CHANNEL_PENDING_FAILURE = "GET_CHANNEL_PENDING_FAILURE"
